Repository Interkarma/daggerfall-unity, pull requests merged in 2019-11, with the labels that each got.

#1596 Increase accessibility of Trade Window for modding purposes
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Labels: enhancement, mod system

#1607 Wagon weight modifiable
  Assets/Scripts/Game/Items/ItemHelper.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Labels: enhancement

#1615 fix a NullReferenceException in DaggerfallVidPlayerWindow.IsPlaying
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
Labels: bug

#1622 fix negative rented room time
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
Labels: bug

#1627 Early customization of SaveGameWindow is now obsolete
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
  Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Labels: mod system
