Repository Interkarma/daggerfall-unity, pull requests merged in 2019-10, with the labels that each got.

#1562 Enable guild modding
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
  Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
  Assets/Scripts/Game/Guilds/Guild.cs
  Assets/Scripts/Game/Guilds/GuildManager.cs
  Assets/Scripts/Game/Guilds/IGuild.cs
  Assets/Scripts/Game/Guilds/IGuild.cs.meta
  Assets/Scripts/Game/Guilds/KnightlyOrder.cs
  Assets/Scripts/Game/Guilds/Temple.cs
  Assets/Scripts/Game/Guilds/ThievesGuild.cs
  Assets/Scripts/Game/PlayerActivate.cs
  Assets/Scripts/Game/TalkManager.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
  Assets/Scripts/Internal/DaggerfallBookshelf.cs
Labels: enhancement, mod system

#1518 Grammar and typo fixes
  Assets/Resources/ItemTemplates.txt
  Assets/Resources/MagicItemTemplates.txt
  Assets/Resources/PotionRecipes.txt
  Assets/Resources/books.txt
  Assets/StreamingAssets/Factions/FACTION.TXT
  Assets/StreamingAssets/Quests/S0000013.txt
  Assets/StreamingAssets/Quests/S0000016.txt
  Assets/StreamingAssets/Quests/S0000988.txt
Labels: enhancement

#1524 Change nature 3d asset replacement to limit performance hit
  Assets/Scripts/Terrain/StreamingWorld.cs
  Assets/Scripts/Terrain/TerrainHelper.cs
  Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Labels: enhancement, mod system

#1540 Fix precision issue with custom dungeon exit doors
  Assets/Scripts/Internal/DaggerfallStaticDoors.cs
Labels: mod system

#1551 Add IPlayerActivable interface for custom activations
  Assets/Scripts/Game/PlayerActivate.cs
Labels: enhancement

#1571 Override world data for locations and dungeons
  Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
  Assets/Scripts/API/BlocksFile.cs
  Assets/Scripts/API/DFBlock.cs
  Assets/Scripts/API/DFLocation.cs
  Assets/Scripts/API/DFRegion.cs
  Assets/Scripts/API/MapsFile.cs
  Assets/Scripts/Game/ExteriorAutomap.cs
  Assets/Scripts/Game/SongManager.cs
  Assets/Scripts/Terrain/TerrainHelper.cs
  Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
  Assets/Scripts/Utility/RDBLayout.cs
Labels: enhancement, mod system

#1570 Support live changes to mod settings
  Assets/Game/Addons/ModSupport/Mod.cs
  Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs
  Assets/Game/Addons/ModSupport/ModSettings/ModSettingsTypes.cs
  Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
  Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
Labels: enhancement, mod system
