Repository Interkarma/daggerfall-unity, pull requests merged in 2019-08, with the labels that each got.

#1406 update region name from notebook fast travel
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Labels: bug

#1405 allow character modifications in summary screen
  Assets/Scripts/Game/UserInterfaceWindows/CreateCharSummary.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Labels: bug

#1407 add console command to open the potion maker
  Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
  Assets/Scripts/Game/DaggerfallUI.cs
  Assets/Scripts/Game/DaggerfallUIMessages.cs
Labels: enhancement

#1432 don't ground player when onboarding ship
  Assets/Scripts/Terrain/StreamingWorld.cs
Labels: bug

#1424 Enable more classic quests, rebalance house cleaning quests
  Assets/StreamingAssets/Quests/A0C00Y07.txt
  Assets/StreamingAssets/Quests/A0C00Y16.txt
  Assets/StreamingAssets/Quests/A0C41Y18.txt
  Assets/StreamingAssets/Quests/B0B81Y02.txt
  Assets/StreamingAssets/Quests/B0C00Y13.txt
  Assets/StreamingAssets/Quests/M0B00Y15.txt
  Assets/StreamingAssets/Quests/M0C00Y14.txt
  Assets/StreamingAssets/Quests/S0000004.txt
  Assets/StreamingAssets/Tables/QuestList-Classic.txt
Labels: questing

#1459 Classic quest fixes, Aug 2019
  Assets/StreamingAssets/Quests/A0C41Y18.txt
  Assets/StreamingAssets/Quests/B0B71Y03.txt
  Assets/StreamingAssets/Quests/D0B00Y00.txt
  Assets/StreamingAssets/Quests/L0A01L00.txt
  Assets/StreamingAssets/Quests/M0B00Y17.txt
  Assets/StreamingAssets/Quests/M0B11Y18.txt
  Assets/StreamingAssets/Quests/M0B1XY01.txt
  Assets/StreamingAssets/Quests/M0B21Y19.txt
  Assets/StreamingAssets/Quests/S0000001.txt
  Assets/StreamingAssets/Tables/QuestList-Classic.txt
Labels: questing

#1464 Add exclusive fullscreen checkbox to advanced video options
  Assets/Resources/defaults.ini.txt
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
  Assets/Scripts/Game/Utility/SceneControl.cs
  Assets/Scripts/Game/Utility/StartGameBehaviour.cs
  Assets/Scripts/SettingsManager.cs
  Assets/StreamingAssets/Text/GameSettings.txt
Labels: enhancement
