Repository Interkarma/daggerfall-unity, pull requests merged in 2019-12, with the labels that each got.

#1567 (de)buff icons sizes and positions
  Assets/Resources/defaults.ini.txt
  Assets/Scripts/Game/UserInterface/HUDActiveSpells.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
  Assets/Scripts/SettingsManager.cs
  Assets/StreamingAssets/Text/GameSettings.txt
Labels: enhancement

#1590 Gold infopanel update
  Assets/Scripts/Game/Items/ItemBuilder.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/StreamingAssets/Text/DaggerfallUI.txt
Labels: enhancement

#1632 make sure dungeons's SongManager updates song with each dungeon
  Assets/Scripts/Game/SongManager.cs
Labels: bug

#1633 don't change footstep sounds during winter under snow-free climates
  Assets/Scripts/Game/PlayerFootsteps.cs
  Assets/Scripts/Game/WeatherManager.cs
Labels: bug

#1629 remove TAB characters from quest messages
  Assets/StreamingAssets/Quests/K0C30Y03.txt
  Assets/StreamingAssets/Quests/S0000009.txt
Labels: bug

#1626 wrap AudioSource.PlayClipAtPoint
  Assets/Scripts/Game/EnemyDeath.cs
  Assets/Scripts/Internal/AudioSourceExtensionMethods.cs
  Assets/Scripts/Internal/DaggerfallAudioSource.cs
Labels: bug

#1625 more standard fasttravel options selection
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Labels: enhancement

#1624 Use brighter green for selected fast travel options
  Assets/Resources/GreenCheckbox.png
  Assets/Resources/GreenCheckbox.png.meta
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Labels: enhancement

#1620 Make previous position of difficulty dagger slowly fade away
  Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
Labels: enhancement

#1616 fix: localized floating numbers handling
  Assets/Game/Addons/ModSupport/ModSettings/ModSettingsTypes.cs
  Assets/Scripts/Game/UserInterface/TextBox.cs
Labels: bug

#1642 Improved support for formula overriding
  Assets/Scripts/External/Func.cs
  Assets/Scripts/External/Func.cs.meta
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
Labels: enhancement

#1519 Show loading text before loading game
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
  Assets/StreamingAssets/Text/DaggerfallUI.txt
Labels: enhancement

#1589 Add the ability to rename saves from the main UI
  Assets/Scripts/Game/Serialization/SaveLoadManager.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
Labels: enhancement

#1595 Add VS Code workspace settings and Json schemas
  .gitignore
  .vscode/settings.json
  Assets/Editor/.Schemas/BookMapping.schema.json
  Assets/Editor/.Schemas/ItemTemplates.schema.json
  Assets/Editor/.Schemas/ModInfo.schema.json
  Assets/Editor/.Schemas/Preset.schema.json
  Assets/Editor/.Schemas/SpellIcons.schema.json
Labels: editor, enhancement

#1600 Show warning for incompatible mods when game is launched
  Assets/Game/Addons/ModSupport/ModManager.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
  Assets/StreamingAssets/Text/MainMenu.txt
Labels: enhancement, mod system

#1598 Support providers of mobile person graphics
  Assets/Scripts/Editor/SetupMobilePersonEditor.cs
  Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
  Assets/Scripts/Game/Entities/PlayerEntity.cs
  Assets/Scripts/Game/MobilePersonMotor.cs
  Assets/Scripts/Game/MobilePersonNPC.cs
  Assets/Scripts/Game/Utility/PopulationManager.cs
  Assets/Scripts/Game/WeaponManager.cs
  Assets/Scripts/Internal/MobilePersonBillboard.cs
Labels: enhancement, mod system

#1601 Add support for mod dependencies
  Assets/Game/Addons/ModSupport/Mod.cs
  Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
  Assets/Game/Addons/ModSupport/ModManager.cs
  Assets/Game/Addons/ModSupport/ModTypes.cs
  Assets/StreamingAssets/Text/ModSystem.txt
Labels: enhancement, mod system

#1638 Show warning if mod is created on unsupported Editor version
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
Labels: editor, mod system

#1643 fix classic load by swapping free action and climbing effects
  Assets/Scripts/Game/MagicAndEffects/Effects/Alteration/Climbing.cs
  Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FreeAction.cs
Labels: bug

#1645 Weapon sounds when hitting walls
  Assets/Scripts/Game/WeaponManager.cs
Labels: enhancement

#1654 <---> separator bug in S00000018
  Assets/StreamingAssets/Quests/S0000018.txt
Labels: bug
