Repository Interkarma/daggerfall-unity, pull requests merged in 2020-04, with the labels that each got.

#1772 Add a blinking cursor to daedra quest Y/N question
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallDaedraSummonedWindow.cs
Labels: enhancement

#1744 Fix left handed bow damage and condition lowering
  Assets/Scripts/Game/WeaponManager.cs
Labels: bug

#1747 Refactor combat formula to enable modding
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
  Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Labels: enhancement, mod system

#1751 Fix bug with breaking armor and enchanting unworn armor
  Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Labels: bug

#1752 Improved robustness of ModManager.TryGetAsset()
  Assets/Game/Addons/ModSupport/Mod.cs
  Assets/Game/Addons/ModSupport/ModManager.cs
Labels: mod system

#1754 ImportedComponentAttribute now supports dependencies
  Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
Labels: enhancement, mod system

#1757 Mod reserved layers
  Assets/Game/Addons/ModSupport/ModTypes.cs
  ProjectSettings/TagManager.asset
Labels: mod system

#1766 Fix dungeon exit and other static door overlap
  Assets/Scripts/Internal/DaggerfallStaticDoors.cs
Labels: bug

#1767 Add furniture category which are present, just rare
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Labels: bug

#1771 Don't (re)stack items during player deserialization
  Assets/Scripts/Game/Items/ItemCollection.cs
Labels: bug

#1762 Enable custom items to be added by mods
  Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
  Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
  Assets/Scripts/Game/Items/ItemBuilder.cs
  Assets/Scripts/Game/Items/ItemEquipTable.cs
  Assets/Scripts/Game/Items/ItemHelper.cs
  Assets/Scripts/Game/UserInterface/ItemListScroller.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs
  Assets/Scripts/Internal/DaggerfallInterior.cs
  Assets/Scripts/Internal/DaggerfallLoot.cs
  Assets/Scripts/Utility/ImageReader.cs
Labels: enhancement, mod system

#1768 Custom flat / model activation
  Assets/Scripts/Game/PlayerActivate.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
  Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
  Assets/Scripts/Utility/GameObjectHelper.cs
  Assets/Scripts/Utility/RDBLayout.cs
Labels: enhancement, mod system

#1775 Support for runtime materials
  Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
  Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs.meta
  Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Labels: mod system

#1785 Remove invalid assets from cache
  Assets/Game/Addons/ModSupport/Mod.cs
Labels: mod system

#1723 Rudimentary Gamepad Support
  Assets/Scenes/DaggerfallUnityGame.unity
  Assets/Scenes/DaggerfallUnityStartup.unity
  Assets/Scripts/Game/HotkeySequence.cs
  Assets/Scripts/Game/InputManager.cs
  Assets/Scripts/Game/PlayerMouseLook.cs
  Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
  Assets/Scripts/Game/UserInterface/HorizontalSlider.cs
  Assets/Scripts/Game/UserInterface/VerticalScrollBar.cs
  Assets/Scripts/Game/UserInterfaceWindows/ColorPicker.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallLoadClassicGameWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
  ProjectSettings/InputManager.asset
Labels: enhancement
