Repository Interkarma/daggerfall-unity, pull requests merged in 2020-09, with the labels that each got.

#1821 Added City Bulletin Boards
  Assets/Scripts/Game/PlayerActivate.cs
  Assets/Scripts/Game/TalkManager.cs
  Assets/Scripts/Utility/RMBLayout.cs
Labels: wip

#1883 Support for precompiled mods (experimental)
  Assets/Game/Addons/ModSupport/Editor/CompilerWindow.cs
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
  Assets/Game/Addons/ModSupport/Editor/ModAssemblyBuilder.cs
  Assets/Game/Addons/ModSupport/Editor/ModAssemblyBuilder.cs.meta
  Assets/Game/Addons/ModSupport/Mod.cs
  Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Labels: mod system

#1908 Implemented cn2 macro for jokes
  Assets/Scripts/Utility/MacroHelper.cs
Labels: bug

#1918 Mod Dependencies Editor
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
  Assets/Game/Addons/ModSupport/Editor/ModDependenciesEditorWindow.cs
  Assets/Game/Addons/ModSupport/Editor/ModDependenciesEditorWindow.cs.meta
  Assets/Game/Addons/ModSupport/ModTypes.cs
Labels: editor, mod system

#1926 Discard virtual mods without a valid title
  Assets/Game/Addons/ModSupport/ModManager.cs
Labels: mod system

#1922 Quest fixes Sept 2020
  Assets/StreamingAssets/Quests/B0B00Y00.txt
  Assets/StreamingAssets/Quests/B0B40Y08.txt
  Assets/StreamingAssets/Quests/B0C00Y06.txt
  Assets/StreamingAssets/Quests/C0B00Y02.txt
  Assets/StreamingAssets/Quests/L0B20Y02.txt
  Assets/StreamingAssets/Quests/R0C11Y26.txt
  Assets/StreamingAssets/Quests/R0C11Y28.txt
Labels: questing

#1925 Minor improvements to mod loader UI
  Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Labels: mod system

#1929 Change Automap toggle to GetKey method
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
Labels: UI

#1931 Remove GC in drawing Panels
  Assets/Scripts/Game/UserInterface/Panel.cs
Labels: UI

#1935 Allow TerrainSamplers to disable the default job and do their own location blending / flattening
  Assets/Scripts/Terrain/DaggerfallTerrain.cs
  Assets/Scripts/Terrain/TerrainSampler.cs
Labels: mod system

#1936 Move material selection into overridable formulas
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
  Assets/Scripts/Game/Items/ItemBuilder.cs
  Assets/Scripts/Game/Items/ItemHelper.cs
  Assets/Scripts/Internal/DaggerfallLoot.cs
Labels: mod system

#1940 Fix SearchItems method when no template index specified
  Assets/Scripts/Game/Items/ItemCollection.cs
Labels: bug
