Repository Interkarma/daggerfall-unity, pull requests merged in 2021-03, with the labels that each got.

#1763 Support custom implementations of mobile units
  Assets/Scripts/Game/EnemyAttack.cs
  Assets/Scripts/Game/EnemyDeath.cs
  Assets/Scripts/Game/EnemyHealth.cs
  Assets/Scripts/Game/EnemyMotor.cs
  Assets/Scripts/Game/EnemySenses.cs
  Assets/Scripts/Game/EnemySounds.cs
  Assets/Scripts/Game/Questing/Actions/CreateFoe.cs
  Assets/Scripts/Game/Serialization/SerializableEnemy.cs
  Assets/Scripts/Game/SetupDemoEnemy.cs
  Assets/Scripts/Game/Utility/FoeSpawner.cs
  Assets/Scripts/Game/WeaponManager.cs
  Assets/Scripts/Internal/Base.meta
  Assets/Scripts/Internal/Base/MobileUnit.cs
  Assets/Scripts/Internal/Base/MobileUnit.cs.meta
  Assets/Scripts/Internal/DaedraSeducerMobileBehaviour.cs
  Assets/Scripts/Internal/DaggerfallEnemy.cs
  Assets/Scripts/Internal/DaggerfallMobileUnit.cs
  Assets/Scripts/Utility/GameObjectHelper.cs
  Assets/Scripts/Utility/RDBLayout.cs
Labels: mod system

#2013 Change removal of Oghma to be handled by effect manager
  Assets/Scripts/Game/MagicAndEffects/Effects/Special/OghmaInfiniumEffect.cs
  Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
  Assets/Scripts/Game/MagicAndEffects/MagicAndEffectsStructs.cs
Labels: bug

#2045 Fix mod asset loading on turkish culture
  Assets/Game/Addons/ModSupport/ModManager.cs
Labels: mod system

#2060 Only interact with large HUD when cursor active on Linux
  Assets/Scripts/Game/UserInterface/HUDLarge.cs
Labels: UI, bug, linux

#2040 Import mod settings after changes
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
  Assets/Game/Addons/ModSupport/ModManager.cs
  Assets/Game/Addons/ModSupport/ModSettings/ModSettingsData.cs
Labels: editor, mod system

#2030 Constant horse jumping capability
  Assets/Scripts/Game/Player/AcrobatMotor.cs
Labels: enhancement

#2059 Toggle large HUD with F10 like classic
  Assets/Scripts/Game/UserInterface/DaggerfallShortcut.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
  Assets/StreamingAssets/Text/DialogShortcuts.txt
Labels: UI, enhancement

#2035 Prevent player location being selected for remote place
  Assets/Scripts/Game/Questing/Place.cs
Labels: bug

#2054 Fixed torch burning ticks progressing while the game is paused
  Assets/Scripts/Game/EnablePlayerTorch.cs
Labels: bug
