Repository Interkarma/daggerfall-unity, pull requests merged in 2021-04, with the labels that each got.

#2020 fix potion maker's stackCounts (take 2, alternative to #2011)
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs
Labels: bug

#2032 Implement right clicks as described in Daggerfall manual
  Assets/Scripts/Game/UserInterface/ItemListScroller.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Labels: enhancement

#2068 Change journal UI window permissions to allow overriding by mods
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
Labels: mod system

#2079 Do not draw TextBox defaultText if null
  Assets/Scripts/Game/UserInterface/TextBox.cs
Labels: UI

#2057 Fix several issues with conjured arrows
  Assets/Scripts/Game/DaggerfallMissile.cs
  Assets/Scripts/Game/Items/ItemCollection.cs
  Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/CreateItem.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
  Assets/Scripts/Game/WeaponManager.cs
Labels: bug

#2097 Resynchronize vital indicators after toggling large HUD
  Assets/Scripts/Game/Player/VitalsChangeDetector.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
Labels: bug
