Repository Interkarma/daggerfall-unity, pull requests merged in 2021-07, with the labels that each got.

#2149 Pass face record id into mobile person asset
  Assets/Scripts/Game/MobilePersonNPC.cs
  Assets/Scripts/Internal/MobilePersonBillboard.cs
Labels: enhancement, mod system

#2166 Fix billboard animation so frame 0 is rendered first
  Assets/Scripts/Internal/DaggerfallBillboard.cs
Labels: bug

#2043 Fix cache issue with climate/season model variants
  Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Labels: mod system

#2141 Fixed "pc at any <location>" guildhall issue
  Assets/Scripts/Game/Questing/Place.cs
Labels: bug

#2146 AI pathfinding issues when getting shot at
  Assets/Scripts/Game/EnemyMotor.cs
Labels: bug

#2147 Colorblind accessibility settings
  Assets/Resources/defaults.ini.txt
  Assets/Scripts/Game/DaggerfallUI.cs
  Assets/Scripts/Game/ExteriorAutomap.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
  Assets/Scripts/SettingsManager.cs
  Assets/StreamingAssets/Text/GameSettings.txt
Labels: enhancement

#2157 Add colliders to custom dungeon models added using "COL" in the World Data Editor I'm working on.
  Assets/Scripts/Utility/RDBLayout.cs
Labels: enhancement, mod system

#2161 Add frame speed divisor to abstract class
  Assets/Scripts/Game/EnemyAttack.cs
  Assets/Scripts/Internal/Base/MobileUnit.cs
  Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Labels: bug, mod system

#2173 Ensure only new locations are picked up from mods
  Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
Labels: bug, mod system

#2160 Modding new mobile textures
  Assets/Scripts/Internal/DaggerfallMobileUnit.cs
  Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Labels: enhancement, mod system
