Repository Interkarma/daggerfall-unity, pull requests merged in 2021-01, with the labels that each got.

#1978 Fix spurious "can't carry any more" when picking maps
  Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Labels: bug

#1979 Fix regression introduced in #1965
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Labels: bug, regression

#1980 more skybox seam fixes
  Assets/Scripts/Internal/DaggerfallSky.cs
Labels: bug

#1983 Stores enabled mod build targets in editor
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
Labels: editor, mod system

#1985 Fix dungeon FM songs (related to #1953)
  Assets/Scripts/Game/SongManager.cs
Labels: bug

#1998 Import mod manifest after changes
  Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
Labels: enhancement, mod system

#1999 Refresh cursor on game start
  Assets/Game/Addons/ModSupport/ModManager.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Labels: mod system
