Repository Interkarma/daggerfall-unity, pull requests merged in 2021-05, with the labels that each got.

#2107 Reset ship ownership on new game start
  Assets/Scripts/Game/DaggerfallBankManager.cs
  Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Labels: bug

#2103 Refactor guild service window
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceCureDisease.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceCureDisease.cs.meta
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceDonation.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceDonation.cs.meta
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceTraining.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceTraining.cs.meta
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/UIWindowFactory.cs
Labels: UI, mod system

#2104 Re-fix riding sprint in mods
  Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
Labels: bug

#2112 Fix typo in DFU macro %pg1
  Assets/Scripts/Utility/MacroHelper.cs
Labels: bug

#2007 Create ITerrainMaterialProvider and allow overriding by mods
  Assets/Scripts/DaggerfallUnity.cs
  Assets/Scripts/Terrain/DaggerfallTerrain.cs
  Assets/Scripts/Terrain/TerrainMaterialProvider.cs
  Assets/Scripts/Terrain/TerrainMaterialProvider.cs.meta
Labels: enhancement

#2094 Quest and enchanted items exclusions
  Assets/Scripts/Game/FPSWeapon.cs
  Assets/Scripts/Game/Items/ItemCollection.cs
  Assets/Scripts/Game/Items/ItemHelper.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs
  Assets/Scripts/Game/WeaponManager.cs
Labels: wip

#2113 Don't reset lastSpell when using magic missile items
  Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Labels: bug

#2098 Modding the character sheet's Skills dialog
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
  Assets/Scripts/Utility/FallbackTextProvider.cs
  Assets/Scripts/Utility/FallbackTextProvider.cs.meta
  Assets/Scripts/Utility/TextProvider.cs
Labels: UI, mod system

#2109 Expose the SpellMaker and its subwindows to mods
  Assets/Scripts/Game/UserInterface/UpDownSpinner.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallEffectSettingsEditorWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellMakerWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/SpellIconPickerWindow.cs
  Assets/Scripts/Game/UserInterfaceWindows/UIWindowFactory.cs
Labels: UI

#2115 Prevent levitating and swimming diagonally from being 40% faster
  Assets/Scripts/Game/LevitateMotor.cs
Labels: bug

#2128 Stack identical books together
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
  Assets/Scripts/Game/Items/ItemCollection.cs
Labels: enhancement
