Repository Interkarma/daggerfall-unity, pull requests merged in 2021-02, with the labels that each got.

#2005 Ensure that the last location is set to current loc when entering a building.
  Assets/Scripts/Game/PlayerEnterExit.cs
  Assets/Scripts/Terrain/TerrainNature.cs
  Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
Labels: bug

#2012 Update paymoney quest action to allow only gold to be accepted if desired
  Assets/Scripts/Game/Questing/Actions/PayMoney.cs
Labels: enhancement

#2022 Add NameSeed to building overrides
  Assets/Scripts/API/BlocksFile.cs
  Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
  Assets/Scripts/Utility/RMBLayout.cs
Labels: enhancement

#2019 Adjust position of item based player torch to throw some visible shadows off static geometry
  Assets/Scripts/Game/EnablePlayerTorch.cs
Labels: enhancement

#2029 Fix dictionary access for non existant keys
  Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
Labels: bug

#2044 Fix mods window all on/off text color
  Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Labels: mod system

#2047 Fixed misnamed formula overrides
  Assets/Scripts/Game/Formulas/FormulaHelper.cs
Labels: bug

#2048 Allow non-member quests to have rep requirements
  Assets/Scripts/Game/Questing/QuestListsManager.cs
Labels: bug

#2037 Don't restrict shields by plate or chain
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Labels: bug
