Repository Interkarma/daggerfall-unity, pull requests merged in 2024-12, with the labels that each got.

#2686 Handle being silenced during casting animation
  Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Labels: bug

#2687 Allow to close console with Escape key
  Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs
  Assets/Scenes/DaggerfallUnityGame.unity
Labels: UI, refinement

#2688 Allow guild quests to be dispensed by player level as well as rank
  Assets/Scripts/Game/Guilds/Guild.cs
  Assets/Scripts/Game/Guilds/IGuild.cs
  Assets/Scripts/Game/Guilds/KnightlyOrder.cs
  Assets/Scripts/Game/Guilds/MagesGuild.cs
  Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
  Assets/StreamingAssets/Tables/QuestList-Classic.txt
Labels: classic variance
