Repository Interkarma/daggerfall-unity, pull requests merged in 2024-08, with the labels that each got.

#2650 Quest item resource mod support
  Assets/Scripts/Game/Questing/Item.cs
Labels: enhancement, mod system

#2665 Fixed the Mod Loader Interface Window's Extract Text in Portable Inst
  Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Labels: bug

#2666 Preserve enemy orientation when hit by the Wabbajack
  Assets/Scripts/Game/MagicAndEffects/Effects/Special/WabbajackEffect.cs
Labels: classic variance

#2671 Fix more one-way staircases
  Assets/Scripts/Internal/DaggerfallInterior.cs
Labels: classic bug

#2675 Use magic items at range while silenced
  Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Labels: classic variance
